export const productsList = [
  {
    title: 'jujutsu kaisen',
    author: 'gege akutami',
    genre: ['Action', 'Supernatural', 'Fantasy'],
    description:
      'In a world where cursed spirits feed on unsuspecting humans, fragments of the legendary and feared demon Ryomen Sukuna have been lost and scattered about. Should any demon consume Sukuna’s body parts, the power they gain could destroy the world as we know it. Fortunately, there exists a mysterious school of jujutsu sorcerers who exist to protect the precarious existence of the living from the Supernatural!Although Yuji Itadori looks like your average teenager, his immense physical strength is something to behold! Every sports club wants him to join, but Itadori would rather hang out with the school outcasts in the Occult Research Club. One day, the club manages to get their hands on a sealed cursed object. Little do they know the terror they’ll unleash when they break the seal...',
    price: 11.99,
    stock: 24,
    coverUrl: 'products/jujutsu_1.jpg',
    images: ['products/jujutsu_2.jpg', 'products/jujutsu_3.jpg'],
    releaseDate: new Date('2012-11-12'),
    rating: 4.8,
    featured: true,
    stripePriceId: 'price_xxxxx_jujutsukaisen',
    trending: true,
    isNew: false,
  },
  {
    title: 'solo levelling',
    author: 'h-goon',
    genre: ['Action', 'Supernatural', 'Fantasy'],
    description:
      'Jinwoo faces off against the Monarchs in the heart of Seoul, but three otherworldly beings prove to be too much even for him. It’s the end of the road for this hunter—except that death means little to the Shadow Monarch, King of the Dead. As Jinwoo confronts the true source of his newfound powers at long last, a hunter who was thought to be lost forever steps in to protect the defenseless body of humanity’s last chance, no matter the cost!',
    price: 20.0,
    stock: 34,
    coverUrl: 'products/levelling_1.jpg',
    images: ['products/levelling_2.jpg', 'products/levelling_3.jpg'],
    releaseDate: new Date('2013-11-12'),
    rating: 4.5,
    featured: true,
    stripePriceId: 'price_xxxxx_sololevelling',
    trending: false,
    isNew: true,
  },
  {
    title: 'my hero academia',
    author: 'kohei horikoshi',
    genre: ['Action', 'Superpower', 'Fantasy'],
    description:
      'What would the world be like if 80 percent of the population manifested superpowers called “Quirks”? Heroes and villains would be battling it out everywhere! Being a hero would mean learning to use your power, but where would you go to study? The Hero Academy of course! But what would you do if you were one of the 20 percent who were born Quirkless?Midoriya’s epic final battle with Shigaraki reaches its earth-shattering crescendo! With Danger Sense stolen away and the villain threatening to wipe Japan off the map, Midoriya has to get really creative with his Quirks to survive. The Second’s plan to smash the vestiges of One For All into the core of Shigaraki’s psychic space is the last chance the heroes have to stop All For One’s grand schemes from coming to fruition. But first, Midoriya has to land a solid punch!',
    price: 11.99,
    stock: 44,
    coverUrl: 'products/academia_1.jpg',
    images: ['products/academia_2.jpg', 'products/academia_3.jpg'],
    releaseDate: new Date('2014-11-12'),
    rating: 4.5,
    featured: true,
    stripePriceId: 'price_xxxxx_myheroacademia',
    trending: false,
    isNew: false,
  },
  {
    title: 'dandadan',
    author: 'yukinobu tatsu',
    genre: ['Action', 'Shonen', 'Seinen'],
    description:
      "Dandadan follows the story of Momo Ayase, a high school girl with a family of spirit mediums, and Ken Takakura, nicknamed 'Okarun' a classmate who is obsessed with the occult. Momo and Okarun find themselves in a debate about the existence of ghosts and aliens. To settle their argument, they decide to visit places rumored to be paranormal hotspots: Momo goes to an abandoned hospital (a supposed UFO hotspot), and Okarun goes to a haunted tunnel. At these locations, they each encounter beings beyond their comprehension. Momo awakens a latent power, while Okarun gains a curse ability. These encounters set them on a path of battling paranormal threats, exploring their developing feelings for each other, and delving deeper into the Supernatural world.",
    price: 29.99,
    stock: 54,
    coverUrl: 'products/dan_1.jpg',
    images: ['products/dan_2.jpg', 'products/dan_3.jpg'],
    releaseDate: new Date('2015-11-12'),
    rating: 4.0,
    featured: false,
    stripePriceId: 'price_xxxxx_dandadan',
    trending: true,
    isNew: false,
  },
  {
    title: 'chainsaw man',
    author: 'tatsuki fujimoto',
    genre: ['Action', 'Sci-fi', 'Seinen'],
    description:
      'Chainsaw Man is a dark fantasy manga series by Tatsuki Fujimoto about Denji, a young man who, after merging with his pet devil Pochita, becomes the titular Chainsaw Man. Fusing with Pochita grants him the ability to transform parts of his body into chainsaws, making him a powerful weapon against devils. He joins the Public Safety Devil Hunters to fight against the devils threatening Japan, battling both powerful devils and exploring themes of violence, power, and survival. The series is known for its unique blend of action, dark humor, and unexpected plot twists, along with its distinctive art style and memorable characters.',
    price: 49.99,
    stock: 64,
    coverUrl: 'products/chain_1.jpg',
    images: ['products/chain_2.jpg', 'products/chain_3.jpg'],
    releaseDate: new Date('2016-11-12'),
    rating: 3.8,
    featured: false,
    stripePriceId: 'price_xxxxx_chainsawman',
    trending: false,
    isNew: true,
  },
  {
    title: 'blue lock',
    author: 'muneyuki kaneshiro',
    genre: ['Soccer', 'Seinen'],
    description:
      'Unable to best Michael Kaiser during training, Isagi was relegated to the bench for Bastard München’s first match against FC Barcha. Despite his frustration, Isagi resolves to analyze every second of the match so he can draw level with the evolved Bachira and Kunigami. But wait... Noel Noa’s coming onto the field?! What follows is a truly epic clash of soccer gods and monsters—one that might even bring Isagi off the bench...',
    price: 33.99,
    stock: 74,
    coverUrl: 'products/blue_1.jpg',
    images: ['products/blue_2.jpg', 'products/blue_3.jpg'],
    releaseDate: new Date('2017-11-12'),
    rating: 3.5,
    featured: false,
    stripePriceId: 'price_xxxxx_bluelock',
    trending: false,
    isNew: false,
  },
  {
    title: 'demon slayer: kimetsu no yaiba',
    author: 'koyoharu gotouge',
    genre: ['Action', 'Seinen', 'Supernatural'],
    description:
      'Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family!In Taisho-era Japan, kindhearted Tanjiro Kamado makes a living selling charcoal. But his peaceful life is shattered when a demon slaughters his entire family. His little sister Nezuko is the only survivor, but she has been transformed into a demon herself! Tanjiro sets out on a dangerous journey to find a way to return his sister to normal and destroy the demon who ruined his life.Learning to destroy demons won’t be easy, and Tanjiro barely knows where to start. The surprise appearance of another boy named Giyu, who seems to know what’s going on, might provide some answers—but only if Tanjiro can stop Giyu from killing his sister first!',
    price: 83.99,
    stock: 84,
    coverUrl: 'products/chain_1.jpg',
    images: ['products/chain_2.jpg', 'products/chain_3.jpg'],
    releaseDate: new Date('2018-11-12'),
    rating: 5.0,
    featured: true,
    stripePriceId: 'price_xxxxx_demonslayer',
    trending: true,
    isNew: false,
  },
  {
    title: 'one piece',
    author: 'eichiro oda',
    genre: ['Action', 'SuperPower', 'Supernatural', 'Adventure'],
    description:
      'Join Monkey D. Luffy and his swashbuckling crew in their search for the ultimate treasure, One Piece!As a child, Monkey D. Luffy dreamed of becoming King of the Pirates. But his life changed when he accidentally gained the power to stretch like rubber...at the cost of never being able to swim again! Years, later, Luffy sets off in search of the “One Piece,” said to be the greatest treasure in the world...As a child, Monkey D. Luffy was inspired to become a pirate by listening to the tales of the buccaneer Red-Haired Shanks. But his life changed when Luffy accidentally ate the Gum-Gum Devil Fruit and gained the power to stretch like rubber...at the cost of never being able to swim again! Years later, still vowing to become the king of the pirates, Luffy sets out on his adventure...one guy alone in a rowboat, in search of the legendary One Piece, said to be the greatest treasure in the world...',
    price: 100.99,
    stock: 94,
    coverUrl: 'products/onepiece_1.jpg',
    images: ['products/onepiece_2.jpg', 'products/onepiece_3.jpg'],
    releaseDate: new Date('2019-11-12'),
    rating: 5.0,
    featured: true,
    stripePriceId: 'price_xxxxx_onepiece',
    trending: false,
    isNew: true,
  },
  {
    title: 'Sakamoto Days',
    author: 'Yuto Suzuki',
    genre: ['Action', 'Comedy', 'Shonen'],
    description:
      'Taro Sakamoto, once the greatest hitman in the underworld, has retired to live a peaceful life as a convenience store owner with his family. But his past refuses to stay buried as old rivals and new threats force him to dust off his deadly skills. Balancing family life with explosive action, Sakamoto Days delivers a thrilling mix of humor and high-stakes battles, perfect for fans of stylish shonen action.',
    price: 12.99,
    stock: 50,
    coverUrl: 'products/sakamoto_1.webp',
    images: ['products/sakamoto_2.webp', 'products/sakamoto_3.webp'],
    releaseDate: new Date('2025-01-15'),
    rating: 4.7,
    featured: true,
    stripePriceId: 'price_xxxxx_sakamotodays',
    trending: true,
    isNew: true,
  },
  {
    title: 'Witch Hat Atelier',
    author: 'Kamome Shirahama',
    genre: ['Fantasy', 'Adventure', 'Shonen'],
    description:
      'In a world where magic is drawn through intricate runes, Coco dreams of becoming a witch despite lacking innate magical talent. When she accidentally discovers the secrets of forbidden magic, she’s thrust into a mesmerizing journey under the tutelage of the enigmatic Qifrey. With breathtaking art and a heartfelt story, Witch Hat Atelier redefines magical adventure for a new generation.',
    price: 14.99,
    stock: 40,
    coverUrl: 'products/witchhat_1.webp',
    images: ['products/witchhat_2.webp', 'products/witchhat_3.jpg'],
    releaseDate: new Date('2025-03-10'),
    rating: 4.6,
    featured: true,
    stripePriceId: 'price_xxxxx_witchhatatelier',
    trending: true,
    isNew: true,
  },
  {
    title: 'Fire Force',
    author: 'Atsushi Ohkubo',
    genre: ['Action', 'Supernatural', 'Shonen'],
    description:
      'In a world consumed by flames, Shinra Kusakabe joins the Fire Force, a team of pyrokinetic fighters battling demonic infernals. As the Great Cataclysm looms, Shinra uncovers dark secrets about the infernals’ origins and his own past. Packed with intense firefights and a unique blend of action and mystery, Fire Force is a blazing addition to any shonen collection.',
    price: 11.99,
    stock: 45,
    coverUrl: 'products/fireforce_1.webp',
    images: ['products/fireforce_2.webp', 'products/fireforce_3.webp'],
    releaseDate: new Date('2025-04-01'),
    rating: 4.4,
    featured: false,
    stripePriceId: 'price_xxxxx_fireforce',
    trending: false,
    isNew: true,
  },
  {
    title: 'Kaiju No. 8',
    author: 'Naoya Matsumoto',
    genre: ['Action', 'Sci-fi', 'Shonen'],
    description:
      'Kafka Hibino dreams of joining the Kaiju Defense Force to fight giant monsters, but his life takes a wild turn when he transforms into a kaiju himself. Now, he must balance his monstrous powers with his human loyalties to protect humanity. With jaw-dropping battles and a relatable hero, Kaiju No. 8 is a monster-sized hit for action fans.',
    price: 13.99,
    stock: 60,
    coverUrl: 'products/kaiju_1.webp',
    images: ['products/kaiju_2.webp', 'products/kaiju_3.webp'],
    releaseDate: new Date('2025-02-20'),
    rating: 4.8,
    featured: true,
    stripePriceId: 'price_xxxxx_kaijuno8',
    trending: true,
    isNew: true,
  },
  {
    title: 'The Apothecary Diaries',
    author: 'Natsu Hyuuga',
    genre: ['Mystery', 'Historical', 'Shojo'],
    description:
      'Maomao, a young apothecary with a knack for poisons, is thrust into the intrigues of the imperial palace. Solving mysteries with her sharp wit and medical knowledge, she navigates a world of political schemes and forbidden romance. This beautifully crafted historical drama blends humor, mystery, and heart for a captivating read.',
    price: 15.99,
    stock: 35,
    coverUrl: 'products/apothecary_1.webp',
    images: ['products/apothecary_2.webp', 'products/apothecary_3.webp'],
    releaseDate: new Date('2025-01-09'),
    rating: 4.5,
    featured: false,
    stripePriceId: 'price_xxxxx_apothecarydiaries',
    trending: false,
    isNew: true,
  },
  {
    title: 'Honey Lemon Soda',
    author: 'Mayu Murata',
    genre: ['Romance', 'Shojo', 'Slice of Life'],
    description:
      'Uka Ishimori, scarred by middle school trauma, struggles to express herself until a chance encounter with a carefree boy and a splash of lemon soda sparks her journey to self-discovery. This heartwarming shojo tale of love and healing is a refreshing addition to any manga shelf, with vibrant art and relatable characters.',
    price: 12.99,
    stock: 50,
    coverUrl: 'products/honeylemon_1.webp',
    images: ['products/honeylemon_2.webp', 'products/honeylemon_3.webp'],
    releaseDate: new Date('2025-02-15'),
    rating: 4.3,
    featured: false,
    stripePriceId: 'price_xxxxx_honeylemonsoda',
    trending: false,
    isNew: true,
  },
  {
    title: 'Gachiakuta',
    author: 'Kei Urana',
    genre: ['Action', 'Fantasy', 'Shonen'],
    description:
      'Rudo, a boy exiled to a trash-filled wasteland called the Pit, discovers his knack for turning junk into weapons to fight monstrous creatures. Fueled by a thirst for revenge, he battles through a gritty, dark fantasy world. Gachiakuta’s raw energy and unique art style make it a standout for fans of intense shonen epics.',
    price: 13.49,
    stock: 40,
    coverUrl: 'products/gachiakuta_1.webp',
    images: ['products/gachiakuta_2.webp', 'products/gachiakuta_3.webp'],
    releaseDate: new Date('2025-06-10'),
    rating: 4.2,
    featured: false,
    stripePriceId: 'price_xxxxx_gachiakuta',
    trending: true,
    isNew: true,
  },

  {
    title: 'Mao',
    author: 'Rumiko Takahashi',
    genre: ['Supernatural', 'Fantasy', 'Shonen'],
    description:
      'Mao, a young exorcist, and Nanoka, a girl who can travel between worlds, team up to battle malevolent spirits in a Taisho-era Japan filled with mystery. From the creator of Inuyasha, Mao weaves a tale of supernatural intrigue and emotional depth, with stunning art and rich storytelling.',
    price: 12.99,
    stock: 50,
    coverUrl: 'products/mao_1.webp',
    images: ['products/mao_2.webp', 'products/mao_3.webp'],
    releaseDate: new Date('2025-04-05'),
    rating: 4.4,
    featured: false,
    stripePriceId: 'price_xxxxx_mao',
    trending: false,
    isNew: true,
  },
  {
    title: 'Ishura',
    author: 'Keiso',
    genre: ['Action', 'Fantasy', 'Isekai'],
    description:
      'After the demon king’s fall, the warriors who defeated him vie for the title of True Hero in a brutal tournament. As demi-gods and golems clash, the world teeters on the brink of another war. Ishura’s intense battles and complex characters make it a gripping addition to the isekai genre.',
    price: 15.49,
    stock: 45,
    coverUrl: 'products/ishura_1.webp',
    images: ['products/ishura_2.jpg', 'products/ishura_3.webp'],
    releaseDate: new Date('2025-03-15'),
    rating: 4.2,
    featured: false,
    stripePriceId: 'price_xxxxx_ishura',
    trending: false,
    isNew: true,
  },
  {
    title: 'Go! Go! Loser Ranger!',
    author: 'Negi Haruba',
    genre: ['Action', 'Comedy', 'Shonen'],
    description:
      'A rebellious foot soldier from an evil army infiltrates the heroic Ranger Force to dismantle it from within. This subversive take on Power Rangers tropes delivers sharp humor and thrilling action, following Fighter D’s antihero journey in a world of flashy heroes and hidden corruption.',
    price: 12.49,
    stock: 55,
    coverUrl: 'products/loserranger_1.webp',
    images: ['products/loserranger_2.webp', 'products/loserranger_3.webp'],
    releaseDate: new Date('2025-05-10'),
    rating: 4.3,
    featured: false,
    stripePriceId: 'price_xxxxx_loserranger',
    trending: true,
    isNew: true,
  },
  {
    title: 'The Summer Hikaru Died',
    author: 'Mokumokuren',
    genre: ['Horror', 'Supernatural', 'Seinen'],
    description:
      'Yoshiki’s best friend Hikaru returns after a mysterious disappearance, but something about him feels... off. As eerie events unfold in their quiet town, Yoshiki uncovers a chilling truth. This haunting manga blends psychological horror with deep emotional resonance, perfect for fans of dark, introspective stories.',
    price: 14.99,
    stock: 30,
    coverUrl: 'products/hikaru_1.webp',
    images: ['products/hikaru_2.webp', 'products/hikaru_3.webp'],
    releaseDate: new Date('2025-06-20'),
    rating: 4.5,
    featured: false,
    stripePriceId: 'price_xxxxx_hikaru',
    trending: false,
    isNew: true,
  },
];
