export const productsList = [
  {
    title: 'jujutsu kaisen',
    author: 'gege akutami',
    genre: ['Action', 'Supernatural', 'Fantasy'],
    description:
      'In a world where cursed spirits feed on unsuspecting humans, fragments of the legendary and feared demon Ryomen Sukuna have been lost and scattered about. Should any demon consume Sukuna’s body parts, the power they gain could destroy the world as we know it. Fortunately, there exists a mysterious school of jujutsu sorcerers who exist to protect the precarious existence of the living from the Supernatural!Although Yuji Itadori looks like your average teenager, his immense physical strength is something to behold! Every sports club wants him to join, but Itadori would rather hang out with the school outcasts in the Occult Research Club. One day, the club manages to get their hands on a sealed cursed object. Little do they know the terror they’ll unleash when they break the seal...',
    price: 11.99,
    stock: 24,
    coverUrl: 'products/jujutsu_1.jpg',
    images: ['products/jujutsu_2.jpg', 'products/jujutsu_3.jpg'],
    releaseDate: new Date('2012-11-12'),
    rating: 4.8,
    featured: true,
    stripePriceId: 'price_xxxxx_jujutsukaisen',
  },
  {
    title: 'solo levelling',
    author: 'h-goon',
    genre: ['Action', 'Supernatural', 'Fantasy'],
    description:
      'Jinwoo faces off against the Monarchs in the heart of Seoul, but three otherworldly beings prove to be too much even for him. It’s the end of the road for this hunter—except that death means little to the Shadow Monarch, King of the Dead. As Jinwoo confronts the true source of his newfound powers at long last, a hunter who was thought to be lost forever steps in to protect the defenseless body of humanity’s last chance, no matter the cost!',
    price: 20.0,
    stock: 34,
    coverUrl: 'products/levelling_1.jpg',
    images: ['products/levelling_2.jpg', 'products/levelling_3.jpg'],
    releaseDate: new Date('2013-11-12'),
    rating: 4.5,
    featured: true,
    stripePriceId: 'price_xxxxx_sololevelling',
  },
  {
    title: 'my hero academia',
    author: 'kohei horikoshi',
    genre: ['Action', 'Superpower', 'Fantasy'],
    description:
      'What would the world be like if 80 percent of the population manifested superpowers called “Quirks”? Heroes and villains would be battling it out everywhere! Being a hero would mean learning to use your power, but where would you go to study? The Hero Academy of course! But what would you do if you were one of the 20 percent who were born Quirkless?Midoriya’s epic final battle with Shigaraki reaches its earth-shattering crescendo! With Danger Sense stolen away and the villain threatening to wipe Japan off the map, Midoriya has to get really creative with his Quirks to survive. The Second’s plan to smash the vestiges of One For All into the core of Shigaraki’s psychic space is the last chance the heroes have to stop All For One’s grand schemes from coming to fruition. But first, Midoriya has to land a solid punch!',
    price: 11.99,
    stock: 44,
    coverUrl: 'products/academia_1.jpg',
    images: ['products/academia_2.jpg', 'products/academia_3.jpg'],
    releaseDate: new Date('2014-11-12'),
    rating: 4.5,
    featured: true,
    stripePriceId: 'price_xxxxx_myheroacademia',
  },
  {
    title: 'dandadan',
    author: 'yukinobu tatsu',
    genre: ['Action', 'Shonen', 'Seinen'],
    description:
      "Dandadan follows the story of Momo Ayase, a high school girl with a family of spirit mediums, and Ken Takakura, nicknamed 'Okarun' a classmate who is obsessed with the occult. Momo and Okarun find themselves in a debate about the existence of ghosts and aliens. To settle their argument, they decide to visit places rumored to be paranormal hotspots: Momo goes to an abandoned hospital (a supposed UFO hotspot), and Okarun goes to a haunted tunnel. At these locations, they each encounter beings beyond their comprehension. Momo awakens a latent power, while Okarun gains a curse ability. These encounters set them on a path of battling paranormal threats, exploring their developing feelings for each other, and delving deeper into the Supernatural world.",
    price: 29.99,
    stock: 54,
    coverUrl: 'products/dan_1.jpg',
    images: ['products/dan_2.jpg', 'products/dan_3.jpg'],
    releaseDate: new Date('2015-11-12'),
    rating: 4.0,
    featured: false,
    stripePriceId: 'price_xxxxx_dandadan',
  },
  {
    title: 'chainsaw man',
    author: 'tatsuki fujimoto',
    genre: ['Action', 'Sci-fi', 'Seinen'],
    description:
      'Chainsaw Man is a dark fantasy manga series by Tatsuki Fujimoto about Denji, a young man who, after merging with his pet devil Pochita, becomes the titular Chainsaw Man. Fusing with Pochita grants him the ability to transform parts of his body into chainsaws, making him a powerful weapon against devils. He joins the Public Safety Devil Hunters to fight against the devils threatening Japan, battling both powerful devils and exploring themes of violence, power, and survival. The series is known for its unique blend of action, dark humor, and unexpected plot twists, along with its distinctive art style and memorable characters.',
    price: 49.99,
    stock: 64,
    coverUrl: 'products/chain_1.jpg',
    images: ['products/chain_2.jpg', 'products/chain_3.jpg'],
    releaseDate: new Date('2016-11-12'),
    rating: 3.8,
    featured: false,
    stripePriceId: 'price_xxxxx_chainsawman',
  },
  {
    title: 'blue lock',
    author: 'muneyuki kaneshiro',
    genre: ['soccer', 'Seinen'],
    description:
      'Unable to best Michael Kaiser during training, Isagi was relegated to the bench for Bastard München’s first match against FC Barcha. Despite his frustration, Isagi resolves to analyze every second of the match so he can draw level with the evolved Bachira and Kunigami. But wait... Noel Noa’s coming onto the field?! What follows is a truly epic clash of soccer gods and monsters—one that might even bring Isagi off the bench...',
    price: 33.99,
    stock: 74,
    coverUrl: 'products/blue_1.jpg',
    images: ['products/blue_2.jpg', 'products/blue_3.jpg'],
    releaseDate: new Date('2017-11-12'),
    rating: 3.5,
    featured: false,
    stripePriceId: 'price_xxxxx_bluelock',
  },
  {
    title: 'demon slayer: kimetsu no yaiba',
    author: 'koyoharu gotouge',
    genre: ['Action', 'Seinen', 'Supernatural'],
    description:
      'Tanjiro sets out on the path of the Demon Slayer to save his sister and avenge his family!In Taisho-era Japan, kindhearted Tanjiro Kamado makes a living selling charcoal. But his peaceful life is shattered when a demon slaughters his entire family. His little sister Nezuko is the only survivor, but she has been transformed into a demon herself! Tanjiro sets out on a dangerous journey to find a way to return his sister to normal and destroy the demon who ruined his life.Learning to destroy demons won’t be easy, and Tanjiro barely knows where to start. The surprise appearance of another boy named Giyu, who seems to know what’s going on, might provide some answers—but only if Tanjiro can stop Giyu from killing his sister first!',
    price: 83.99,
    stock: 84,
    coverUrl: 'products/chain_1.jpg',
    images: ['products/chain_2.jpg', 'products/chain_3.jpg'],
    releaseDate: new Date('2018-11-12'),
    rating: 5.0,
    featured: true,
    stripePriceId: 'price_xxxxx_demonslayer',
  },
  {
    title: 'one piece',
    author: 'eichiro oda',
    genre: ['Action', 'SuperPower', 'Supernatural', 'Adventure'],
    description:
      'Join Monkey D. Luffy and his swashbuckling crew in their search for the ultimate treasure, One Piece!As a child, Monkey D. Luffy dreamed of becoming King of the Pirates. But his life changed when he accidentally gained the power to stretch like rubber...at the cost of never being able to swim again! Years, later, Luffy sets off in search of the “One Piece,” said to be the greatest treasure in the world...As a child, Monkey D. Luffy was inspired to become a pirate by listening to the tales of the buccaneer Red-Haired Shanks. But his life changed when Luffy accidentally ate the Gum-Gum Devil Fruit and gained the power to stretch like rubber...at the cost of never being able to swim again! Years later, still vowing to become the king of the pirates, Luffy sets out on his adventure...one guy alone in a rowboat, in search of the legendary One Piece, said to be the greatest treasure in the world...',
    price: 100.99,
    stock: 94,
    coverUrl: 'products/onepiece_1.jpg',
    images: ['products/onepiece_2.jpg', 'products/onepiece_3.jpg'],
    releaseDate: new Date('2019-11-12'),
    rating: 5.0,
    featured: true,
    stripePriceId: 'price_xxxxx_onepiece',
  },
];
